version: '3.7'

services:
  crawler:
    image: steveimm/sejong-crawler:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./sejong-crawler.sqlite:/app/sejong-crawler/sejong-crawler.sqlite
